export interface FAQ {
  question: string;
  answer: string;
  categories: string[]; // Add categories for better filtering
}

const TEXT_TOOLS_FAQS: FAQ[] = [
  // Word Counter FAQs
  {
    question: "What is a word counter and how does it work?",
    answer: "A word counter is a tool that analyzes text and provides statistics including word count, character count, sentence count, and paragraph count. It's essential for writers, students, and professionals who need to meet specific length requirements for essays, articles, or social media posts.",
    categories: ["word-counter", "general"]
  },
  {
    question: "How do I count words in my document?",
    answer: "Simply paste or type your text into the word counter textarea. The tool automatically counts words in real-time as you type. Words are defined as text separated by spaces, and the count updates instantly.",
    categories: ["word-counter"]
  },
  {
    question: "What is the reading time calculation based on?",
    answer: "Reading time is calculated based on an average reading speed of 200 words per minute, which is the standard for adult readers. This helps you estimate how long it will take someone to read your content.",
    categories: ["word-counter"]
  },

  // Character Counter FAQs
  {
    question: "How accurate is the character counter?",
    answer: "Our character counter is 100% accurate and counts all characters including letters, numbers, spaces, and special characters. It also provides a count without spaces for more detailed analysis.",
    categories: ["character-counter", "general"]
  },
  {
    question: "What's the difference between characters and characters without spaces?",
    answer: "Total characters includes everything (letters, numbers, spaces, symbols). Characters without spaces excludes all whitespace, giving you a count of only visible characters. Both metrics are useful for different purposes like Twitter character limits or SMS message length.",
    categories: ["character-counter"]
  },
  {
    question: "Can the character counter work with different languages?",
    answer: "Yes! Our character counter works with all languages including English, Spanish, French, German, Chinese, Japanese, Arabic, and more. It accurately counts Unicode characters from any language.",
    categories: ["character-counter"]
  },

  // Case Converter FAQs
  {
    question: "What case conversion options are available?",
    answer: "Our case converter supports multiple formats: UPPERCASE (all caps), lowercase (all small), Title Case (First Letter Of Each Word), Sentence case (first letter capitalized), and aLtErNaTe CaSe (alternating between upper and lower).",
    categories: ["case-converter", "general"]
  },
  {
    question: "How do I convert text to uppercase or lowercase?",
    answer: "Paste your text into the case converter, then click the button for your desired format (UPPERCASE, lowercase, Title Case, etc.). The converted text appears instantly and can be copied with one click.",
    categories: ["case-converter"]
  },
  {
    question: "Does case conversion work with accented characters?",
    answer: "Yes! The case converter properly handles accented characters and special letters from various languages, maintaining the correct capitalization rules for international characters.",
    categories: ["case-converter"]
  },

  // Fancy Font Generator FAQs
  {
    question: "Can I use fancy fonts on social media?",
    answer: "Yes! The fancy fonts generated by our tool are Unicode characters that work across all major platforms including Instagram, Twitter, Facebook, TikTok, and WhatsApp. They're not actual fonts but special Unicode characters.",
    categories: ["fancy-font", "general"]
  },
  {
    question: "How many font styles are available in the fancy font generator?",
    answer: "We offer 8+ different font styles including bold, italic, script, double-struck, bubble, square, upside-down, and wide text. All styles are generated instantly and free to use.",
    categories: ["fancy-font"]
  },
  {
    question: "Will fancy fonts work on Instagram and TikTok?",
    answer: "Absolutely! Fancy fonts work perfectly on Instagram bios, posts, stories, TikTok captions, Twitter tweets, Facebook posts, and all other major social media platforms. Just copy and paste.",
    categories: ["fancy-font"]
  },

  // Remove Extra Spaces FAQs
  {
    question: "How do I remove extra spaces from text?",
    answer: "Simply paste your text into the Remove Extra Spaces tool. It will automatically eliminate multiple consecutive spaces, leaving only single spaces between words. You can also remove all spaces entirely if needed.",
    categories: ["remove-spaces", "general"]
  },
  {
    question: "What's the difference between removing extra spaces and removing all spaces?",
    answer: "Remove Extra Spaces keeps single spaces between words but removes multiple consecutive spaces, making text properly formatted. Remove All Spaces eliminates every space character, creating continuous text with no spaces at all.",
    categories: ["remove-spaces"]
  },
  {
    question: "Why does my copied text have extra spaces?",
    answer: "Extra spaces often occur when copying text from PDFs, websites, emails, or formatted documents. Different formatting systems can add multiple spaces, tabs, or whitespace that needs to be cleaned up.",
    categories: ["remove-spaces"]
  },

  // Line Break Remover FAQs
  {
    question: "How do I remove line breaks from text?",
    answer: "Paste your multi-line text into the Line Break Remover tool and click the 'Remove Line Breaks' button. It converts all line breaks into spaces and removes extra spacing, creating a single continuous line.",
    categories: ["line-break-remover", "general"]
  },
  {
    question: "Will removing line breaks preserve word spacing?",
    answer: "Yes! The tool replaces line breaks with spaces and then removes any extra spaces, ensuring words remain properly separated with single spaces. Your text stays readable and well-formatted.",
    categories: ["line-break-remover"]
  },

  // Text Sorter FAQs
  {
    question: "What does the text sorter do?",
    answer: "The text sorter arranges lines of text in alphabetical order (A-Z or Z-A). It's perfect for organizing lists, names, or any data that needs to be alphabetically sorted.",
    categories: ["text-sorter", "general"]
  },
  {
    question: "Can I sort numbers with the text sorter?",
    answer: "Yes! The tool can sort lines that start with numbers. However, it sorts them as text (1, 10, 2, 20) rather than numerically (1, 2, 10, 20). For numeric sorting, ensure numbers have leading zeros (01, 02, 10, 20).",
    categories: ["text-sorter"]
  },
  {
    question: "Does the text sorter remove duplicate lines?",
    answer: "No, the text sorter only arranges lines alphabetically. To remove duplicates, use our Duplicate Line Remover tool. You can use both tools together: first remove duplicates, then sort alphabetically.",
    categories: ["text-sorter"]
  },

  // Duplicate Remover FAQs
  {
    question: "How does the duplicate line remover work?",
    answer: "The duplicate remover scans your text line by line and eliminates any repeated lines, keeping only unique entries. It's useful for cleaning up lists, email addresses, or any data with duplicate entries.",
    categories: ["duplicate-remover", "general"]
  },
  {
    question: "Is duplicate removal case-sensitive?",
    answer: "Yes, the duplicate detection is case-sensitive by default. This means 'Apple' and 'apple' are treated as different lines. Both will be kept in the result unless they are exactly identical including capitalization.",
    categories: ["duplicate-remover"]
  },
  {
    question: "Can I remove duplicates from email lists?",
    answer: "Absolutely! This tool is perfect for cleaning up email lists. Paste your email addresses with one per line, and the tool will remove any duplicate email addresses, ensuring each recipient appears only once.",
    categories: ["duplicate-remover"]
  },

  // Text to Emoji FAQs
  {
    question: "Is the Text to Emoji converter free?",
    answer: "Yes, all our text tools including the Text to Emoji converter are completely free to use. Convert your text to fun emoji representations without any limitations.",
    categories: ["text-to-emoji", "general"]
  },
  {
    question: "What emoji styles are available?",
    answer: "We offer two emoji styles: Style 1 uses emoji symbols (like 🅰️ for A, 🅱️ for B), while Style 2 uses regional indicator symbols (like 🇦 for A). Both styles work on all social media platforms.",
    categories: ["text-to-emoji"]
  },
  {
    question: "Can emoji text be used in Instagram captions?",
    answer: "Yes! Emoji text works perfectly in Instagram captions, bios, stories, Twitter tweets, Facebook posts, and all other social media platforms. These are standard Unicode emojis that display consistently everywhere.",
    categories: ["text-to-emoji"]
  },

  // Reverse Text FAQs
  {
    question: "What can I do with the reverse text generator?",
    answer: "The reverse text generator can reverse text in three ways: reverse all characters (mirror text), reverse word order, or reverse line order. It's fun for creating mirror text, puzzles, or encoding messages.",
    categories: ["reverse-text", "general"]
  },
  {
    question: "How do I create backwards text?",
    answer: "Type or paste your text into the Reverse Text Generator. Choose 'Reverse Characters' to flip all text backwards (Hello → olleH), creating mirror or backwards text instantly.",
    categories: ["reverse-text"]
  },
  {
    question: "Can reversed text be used on social media?",
    answer: "Yes! Reversed text works on all social media platforms and can create interesting visual effects. It's popular for creative posts, puzzles, and unique content on Instagram, Twitter, and Facebook.",
    categories: ["reverse-text"]
  },

  // General FAQs
  {
    question: "Are these text tools safe to use?",
    answer: "Absolutely! All processing happens in your browser. Your text is never sent to our servers or stored anywhere. Your privacy and data security are completely protected.",
    categories: ["general"]
  },
  {
    question: "Can I copy the results?",
    answer: "Yes! Every tool includes a 'Copy to Clipboard' button for instant copying of results. Simply click the copy button and paste the transformed text anywhere you need.",
    categories: ["general"]
  },
  {
    question: "Do I need to create an account?",
    answer: "No account needed! All text tools are instantly accessible without registration, login, or any personal information. Just visit and start using them right away.",
    categories: ["general"]
  },
  {
    question: "Do the tools work offline?",
    answer: "Yes! Once the page is loaded, all tools work entirely in your browser without needing an internet connection. Your text is processed locally for maximum privacy and speed.",
    categories: ["general"]
  },
  {
    question: "Are there any usage limits?",
    answer: "No! All tools are completely free with unlimited usage. There are no character limits, no daily limits, and no premium features. Use as much as you need, whenever you need.",
    categories: ["general"]
  }
];

export default TEXT_TOOLS_FAQS;