export const fancyFontFaqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "Do fancy fonts work on Instagram?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes! All fancy fonts generated by our tool are Unicode characters that work perfectly on Instagram, Twitter, Facebook, TikTok, and other social media platforms. Simply copy and paste."
      }
    },
    {
      "@type": "Question",
      "name": "How many font styles are available?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "We offer 8+ different font styles including bold, italic, script, double-struck, bubble, square, upside-down, and wide text. All styles are free to use."
      }
    },
    {
      "@type": "Question",
      "name": "Are these real fonts?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "These aren't actual fonts but special Unicode characters that look like different font styles. This is why they work across all platforms without needing font installation."
      }
    }
  ]
};