
export const tools = [
  // ── FINANCE TOOLS ──

  {
    href: "/finance-calculators",
    icon: "🏦",
    tag: "Live",
    tagClass: "tag-live",
    name: "Financial Calculators Hub",
    desc: "All-in-one hub for EMI, GST, SIP, Tax, FD, Loan and more. Open the full calculator suite.",
    path: "/finance-calculators",
    cat: "finance",
    related: ["gst", "sip", "tax", "loan", "fd"],
  },
  {
    href: "/finance-calculators/emi",
    icon: "🧮",
    tag: "Live",
    tagClass: "tag-live",
    name: "EMI Calculator",
    desc: "Monthly installments for home, car & personal loans with amortization breakdown.",
    path: "/finance-calculators/emi",
    cat: "finance",
    related: ["gst", "sip", "tax", "loan", "fd"],
  },
  {
    href: "/finance-calculators/gst",
    icon: "🧾",
    tag: "Live",
    tagClass: "tag-live",
    name: "GST Calculator",
    desc: "Add or remove GST instantly. Full CGST/SGST/IGST split for all Indian tax rates.",
    path: "/finance-calculators/gst",
    cat: "finance",
  },
  {
    href: "/finance-calculators/tax",
    icon: "📋",
    tag: "Live",
    tagClass: "tag-live",
    name: "Income Tax",
    desc: "FY 2025–26 tax computation. Old vs New regime comparison with net take-home.",
    path: "/finance-calculators/tax",
    cat: "finance",
  },
  {
    href: "/finance-calculators/sip",
    icon: "📈",
    tag: "Live",
    tagClass: "tag-live",
    name: "SIP Calculator",
    desc: "Project SIP wealth over time with step-up mode, milestones & inflation-adjusted returns.",
    path: "/finance-calculators/sip",
    cat: "finance",
  },
  {
    href: "/finance-calculators/loan",
    icon: "🏛️",
    tag: "Live",
    tagClass: "tag-live",
    name: "Loan Eligibility",
    desc: "Know your maximum loan amount. FOIR-based with CIBIL score adjustment.",
    path: "/finance-calculators/loan",
    cat: "finance",
  },
  {
    href: "/finance-calculators/fd",
    icon: "💰",
    tag: "Live",
    tagClass: "tag-live",
    name: "FD / RD Calculator",
    desc: "Fixed & recurring deposit maturity, compounding frequency comparison.",
    path: "/finance-calculators/fd",
    cat: "finance",
  },
  {
    href: "/finance-calculators/retirement",
    icon: "🌅",
    tag: "Live",
    tagClass: "tag-live",
    name: "Retirement Planner",
    desc: "Corpus needed, SIP gap analysis and inflation-adjusted projections.",
    path: "/finance-calculators/retirement",
    cat: "finance",
  },
  {
    href: "/finance-calculators/networth",
    icon: "💎",
    tag: "Live",
    tagClass: "tag-live",
    name: "Net Worth Tracker",
    desc: "Track assets vs liabilities, donut breakdown and financial health score.",
    path: "/finance-calculators/networth",
    cat: "finance",
  },
  {
    href: "/finance-calculators/goal",
    icon: "🎯",
    tag: "Live",
    tagClass: "tag-live",
    name: "Goal-Based Savings",
    desc: "Plan for home, car, education — with inflation-adjusted SIP targets.",
    path: "/finance-calculators/goal",
    cat: "finance",
  },


  // ── MEDIA ──
  {
    href: "/reel-scheduler",
    icon: "🎬",
    tag: "Soon",
    tagClass: "tag-coming",
    name: "Reel Scheduler",
    desc: "Plan and schedule your Instagram Reels and short-form content with smart timing recommendations.",
    path: "/reel-scheduler",
    cat: "media",
  },

  // ── DEV ──
  {
    href: "/tools/pdf-converter",
    icon: "📄",
    // tag: "New",
    // tagClass: "tag-new",
    tag: "Soon",
    tagClass: "tag-coming",
    name: "PDF Converter",
    desc: "Convert documents between PDF, Word, and image formats directly in your browser — no uploads.",
    path: "/tools/pdf-converter",
    cat: "dev",
  },
  {
    href: "/tools/color-picker",
    icon: "🎨",
    tag: "Soon",
    tagClass: "tag-coming",
    name: "Color Palette Gen",
    desc: "Generate accessible color palettes from a single hex. Export to CSS, Figma, or Tailwind format.",
    path: "/tools/color-picker",
    cat: "dev",
  },

  // ── PRODUCTIVITY ──
  // {
  //   href: "/tools/pomodoro",
  //   icon: "⏱",
  //   tag: "Soon",
  //   tagClass: "tag-coming",
  //   name: "Focus Timer",
  //   desc: "Distraction-free Pomodoro timer with session tracking, streaks, and daily focus reports.",
  //   path: "/tools/pomodoro",
  //   cat: "productivity",
  // },
  {
    href: "/tools/online-notepad",
    icon: "📝",
    // tag: "New",
    tag: "Live",
    tagClass: "tag-new",
    name: "Notepad",
    desc: "Distraction-free notepad with word count, font controls, auto-save to browser, and .txt download.",
    path: "/tools/online-notepad",
    cat: "productivity",
  },
  {
    href: "/tools/pomodoro-timer",
    icon: "⏰",
    // tag: "New",
    tag: "Live",
    tagClass: "tag-new",
    name: "Focus Timer",
    desc: "Distraction-free Focus timer with session tracking, streaks, and daily focus reports.",
    path: "/tools/pomodoro-timer",
    cat: "productivity",
  },


];