export const tools = [
  // ── FINANCE TOOLS ──

  {
    href: "/finance-calculators",
    icon: "🏦",
    tag: "Live",
    tagClass: "tag-live",
    name: "Financial Calculators Hub",
    desc: "All-in-one hub for EMI, GST, SIP, Tax, FD, Loan and more. Open the full calculator suite.",
    path: "/finance-calculators",
    cat: "finance",
    related: ["gst", "sip", "tax", "loan", "fd"],
  },
  {
    href: "/finance-calculators/emi",
    icon: "🧮",
    tag: "Live",
    tagClass: "tag-live",
    name: "EMI Calculator",
    desc: "Monthly installments for home, car & personal loans with amortization breakdown.",
    path: "/finance-calculators/emi",
    cat: "finance",
    related: ["gst", "sip", "tax", "loan", "fd"],
  },
  {
    href: "/finance-calculators/gst",
    icon: "🧾",
    tag: "Live",
    tagClass: "tag-live",
    name: "GST Calculator",
    desc: "Add or remove GST instantly. Full CGST/SGST/IGST split for all Indian tax rates.",
    path: "/finance-calculators/gst",
    cat: "finance",
    related: ["emi", "sip", "tax", "loan", "fd"],
  },
  {
    href: "/finance-calculators/tax",
    icon: "📋",
    tag: "Live",
    tagClass: "tag-live",
    name: "Income Tax",
    desc: "FY 2025–26 tax computation. Old vs New regime comparison with net take-home.",
    path: "/finance-calculators/tax",
    cat: "finance",
    related: ["emi", "gst", "sip", "loan", "fd"],
  },
  {
    href: "/finance-calculators/sip",
    icon: "📈",
    tag: "Live",
    tagClass: "tag-live",
    name: "SIP Calculator",
    desc: "Project SIP wealth over time with step-up mode, milestones & inflation-adjusted returns.",
    path: "/finance-calculators/sip",
    cat: "finance",
    related: ["emi", "gst", "tax", "loan", "fd"],
  },
  {
    href: "/finance-calculators/loan",
    icon: "🏛️",
    tag: "Live",
    tagClass: "tag-live",
    name: "Loan Eligibility",
    desc: "Know your maximum loan amount. FOIR-based with CIBIL score adjustment.",
    path: "/finance-calculators/loan",
    cat: "finance",
    related: ["emi", "gst", "tax", "sip", "fd"],
  },
  {
    href: "/finance-calculators/fd",
    icon: "💰",
    tag: "Live",
    tagClass: "tag-live",
    name: "FD / RD Calculator",
    desc: "Fixed & recurring deposit maturity, compounding frequency comparison.",
    path: "/finance-calculators/fd",
    cat: "finance",
    related: ["emi", "gst", "tax", "sip", "loan"],
  },
  {
    href: "/finance-calculators/retirement",
    icon: "🌅",
    tag: "Live",
    tagClass: "tag-live",
    name: "Retirement Planner",
    desc: "Corpus needed, SIP gap analysis and inflation-adjusted projections.",
    path: "/finance-calculators/retirement",
    cat: "finance",
    related: ["emi", "gst", "tax", "sip", "loan", "fd"],
  },
  {
    href: "/finance-calculators/networth",
    icon: "💎",
    tag: "Live",
    tagClass: "tag-live",
    name: "Net Worth Tracker",
    desc: "Track assets vs liabilities, donut breakdown and financial health score.",
    path: "/finance-calculators/networth",
    cat: "finance",
    related: ["emi", "gst", "tax", "sip", "loan", "fd"],
  },
  {
    href: "/finance-calculators/goal",
    icon: "🎯",
    tag: "Live",
    tagClass: "tag-live",
    name: "Goal-Based Savings",
    desc: "Plan for home, car, education — with inflation-adjusted SIP targets.",
    path: "/finance-calculators/goal",
    cat: "finance",
    related: ["emi", "gst", "tax", "sip", "loan", "fd"],
  },


  // ── MEDIA ──
  {
    href: "/reel-scheduler",
    icon: "🎬",
    tag: "Soon",
    tagClass: "tag-coming",
    name: "Reel Scheduler",
    desc: "Plan and schedule your Instagram Reels and short-form content with smart timing recommendations.",
    path: "/reel-scheduler",
    cat: "media",
    related: [],
  },

  // ── DEV ──
  {
    href: "/tools/json-formatter",
    icon: "📋",
    tag: "Live",
    tagClass: "tag-live",
    name: "JSON Formatter",
    desc: "Beautify, validate, minify and explore JSON with tree view, syntax highlighting and error detection.",
    path: "/tools/Json-formatter",
    cat: "dev",
    related: ["/tools/Base64client", "/tools/url-encoder-decoder", "/tools/html-minifier", "/tools/css-minifier", "/tools/pdf-converter", "/tools/color-picker", "/tools/crypto-encrypt-decrypt"],
  },
  {
    href: "/tools/base-64-client",
    icon: "🔐",
    tag: "Live",
    tagClass: "tag-live",
    name: "Base64 Encode / Decode",
    desc: "Encode text or files to Base64, decode Base64 strings. Supports UTF-8, URL-safe mode and image preview.",
    path: "/tools/Base64client",
    cat: "dev",
    related: ["/tools/json-formatter", "/tools/url-encoder-decoder", "/tools/html-minifier", "/tools/css-minifier", "/tools/pdf-converter", "/tools/color-picker", "/tools/crypto-encrypt-decrypt"],
  },
  {
    href: "/tools/url-encoder-decoder",
    icon: "🔗",
    tag: "Live",
    tagClass: "tag-live",
    name: "URL Encoder / Decoder",
    desc: "Encode special characters for safe URL transmission, decode percent-encoded strings. Parse URL into parts.",
    path: "/tools/url-encoder-decoder",
    cat: "dev",
    related: ["/tools/json-formatter", "/tools/Base64client", "/tools/html-minifier", "/tools/css-minifier", "/tools/pdf-converter", "/tools/color-picker", "/tools/crypto-encrypt-decrypt"],
  },
  {
    href: "/tools/html-minifier",
    icon: "🗜️",
    tag: "Live",
    tagClass: "tag-live",
    name: "HTML Minifier",
    desc: "Compress HTML by removing whitespace, comments and optional tags. See exact byte savings instantly.",
    path: "/tools/html-minifier",
    cat: "dev",
    related: ["/tools/json-formatter", "/tools/Base64client", "/tools/url-encoder-decoder", "/tools/css-minifier", "/tools/pdf-converter", "/tools/color-picker", "/tools/crypto-encrypt-decrypt"],
  },
  {
    href: "/tools/css-minifier",
    icon: "✨",
    tag: "Live",
    tagClass: "tag-live",
    name: "CSS Minifier",
    desc: "Minify CSS by collapsing whitespace, shortening hex colors and removing redundant semicolons.",
    path: "/tools/css-minifier",
    cat: "dev",
    related: ["/tools/json-formatter", "/tools/Base64client", "/tools/url-encoder-decoder", "/tools/html-minifier", "/tools/pdf-converter", "/tools/color-picker", "/tools/crypto-encrypt-decrypt"],
  },
  {
    href: "/tools/pdf-converter",
    icon: "📄",
    tag: "Soon",
    tagClass: "tag-coming",
    name: "PDF Converter",
    desc: "Convert documents between PDF, Word, and image formats directly in your browser — no uploads.",
    path: "/tools/pdf-converter",
    cat: "dev",
    related: ["/tools/json-formatter", "/tools/Base64client", "/tools/url-encoder-decoder", "/tools/html-minifier", "/tools/css-minifier", "/tools/color-picker", "/tools/crypto-encrypt-decrypt"],
  },
  {
    href: "/tools/color-picker",
    icon: "🎨",
    tag: "Soon",
    tagClass: "tag-coming",
    name: "Color Palette Gen",
    desc: "Generate accessible color palettes from a single hex. Export to CSS, Figma, or Tailwind format.",
    path: "/tools/color-picker",
    cat: "dev",
    related: ["/tools/json-formatter", "/tools/Base64client", "/tools/url-encoder-decoder", "/tools/html-minifier", "/tools/css-minifier", "/tools/pdf-converter", "/tools/crypto-encrypt-decrypt"],
  },
    {
    href: "/tools/crypto-encrypt-decrypt",
    icon: "🔑",
    tag: "Live",
    tagClass: "tag-new",
    name: "AES Encrypt/Decrypt",
    desc: "Free online AES encryption and decryption tool. Securely encrypt and decrypt your data in the browser.",
    path: "/tools/crypto-encrypt-decrypt",
    cat: "dev",
    related: ["/tools/json-formatter", "/tools/Base64client", "/tools/url-encoder-decoder", "/tools/html-minifier", "/tools/css-minifier", "/tools/pdf-converter", "/tools/color-picker"],
  },

  

  // ── PRODUCTIVITY ──
  {
    href: "/tools/online-notepad",
    icon: "📝",
    tag: "Live",
    tagClass: "tag-new",
    name: "Notepad",
    desc: "Distraction-free notepad with word count, font controls, auto-save to browser, and .txt download.",
    path: "/tools/online-notepad",
    cat: "productivity",
    related: ["/tools/online-todo-list", "/tools/pomodoro-timer", "/tools/png-to-jpg", "/tools/jpg-to-png"],
  },
  {
    href: "/tools/pomodoro-timer",
    icon: "⏰",
    tag: "Live",
    tagClass: "tag-new",
    name: "Focus Timer",
    desc: "Distraction-free Focus timer with session tracking, streaks, and daily focus reports.",
    path: "/tools/pomodoro-timer",
    cat: "productivity",
    related: ["/tools/online-todo-list", "/tools/pomodoro-timer", "/tools/png-to-jpg", "/tools/jpg-to-png"],
  },

  {
    href: "/tools/images/png-to-jpg",
    icon: "�️",
    tag: "Live",
    tagClass: "tag-new",
    name: "PNG to JPG Converter",
    desc: "Convert PNG images to JPG format online. Adjust output quality, preserve transparency with white background, and download instantly.",
    path: "/tools/images/png-to-jpg",
    cat: "productivity",
    related: ["/tools/online-todo-list", "/tools/pomodoro-timer", "/tools/images/png-to-jpg", "/tools/images/jpg-to-png"],
  },

  {
    href: "/tools/images/jpg-to-png",
    icon: "️",
    tag: "Live",
    tagClass: "tag-new",
    name: "JPG to PNG Converter",
    desc: "Convert JPG images to PNG format online. Adjust output quality, preserve transparency with white background, and download instantly.",
    path: "/tools/images/jpg-to-png",
    cat: "productivity",
    related: ["/tools/online-todo-list", "/tools/pomodoro-timer", "/tools/images/png-to-jpg", "/tools/images/jpg-to-png"],
  },

  {
    href: "/tools/images/Universal-image-converter",
    icon: "️",
    tag: "Live",
    tagClass: "tag-new",
    name: "Universal Image Converter",
    desc: "Convert images between various formats online. Adjust output quality, preserve transparency with white background, and download instantly.",
    path: "/tools/images/Universal-image-converter",
    cat: "productivity",
    related: ["/tools/online-todo-list", "/tools/pomodoro-timer", "/tools/images/png-to-jpg", "/tools/images/jpg-to-png", "/tools/images/Universal-image-converter"],
  },
];