"use client";
import { useState } from "react";

const toc = [
  { id: "acceptance",  label: "Acceptance" },
  { id: "access",      label: "Access & Use" },
  { id: "ip",          label: "Intellectual Property" },
  { id: "conduct",     label: "Prohibited Conduct" },
  { id: "accuracy",    label: "Accuracy of Tools" },
  { id: "liability",   label: "Limitation of Liability" },
  { id: "changes",     label: "Changes to Terms" },
  { id: "governing",   label: "Governing Law" },
  { id: "contact",     label: "Contact" },
];

export default function TermsPage() {
  const [mobileNavOpen, setMobileNavOpen] = useState(false);

  return (
    <>
      <nav id="navbar">
        <a href="/" className="logo">
          <div className="logo-icon">⚒</div>
          ForgeCodeHub
        </a>
        <ul className="nav-links">
          <li><a href="/#tools">Tools</a></li>
          <li><a href="/#how">How it works</a></li>
          <li><a href="/#about">About</a></li>
          <li><a href="/#contact">Contact</a></li>
        </ul>
        <div className="hamburger" onClick={() => setMobileNavOpen(true)}>
          <span /><span /><span />
        </div>
      </nav>

      <div className={`mobile-nav ${mobileNavOpen ? "open" : ""}`}>
        <button className="mobile-nav-close" onClick={() => setMobileNavOpen(false)}>✕</button>
        {["tools","how","about","contact"].map((id) => (
          <a key={id} href={`/#${id}`} onClick={() => setMobileNavOpen(false)}>
            {id.charAt(0).toUpperCase() + id.slice(1)}
          </a>
        ))}
      </div>

      <section className="legal-hero">
        <div className="hero-orb" />
        <div className="container" style={{ textAlign: "center" }}>
          <div className="hero-badge">📜 Legal</div>
          <h1 className="legal-h1">
            Terms &amp;<br />
            <span className="line2">Conditions</span>
          </h1>
          <p className="legal-hero-sub">
            Plain-language terms. No dark patterns, no gotchas — just what you need
            to know to use ForgeCodeHub responsibly.
          </p>
          <div className="legal-meta">
            <span>Last updated: January 1, 2025</span>
            <span className="legal-meta-dot" />
            <span>Effective immediately</span>
          </div>
        </div>
      </section>

      <div className="legal-rule" />

      <section style={{ paddingTop: "4rem", paddingBottom: "6rem" }}>
        <div className="container legal-grid">

          <aside className="legal-sidebar">
            <p className="legal-toc-title">Contents</p>
            {toc.map(({ id, label }) => (
              <a key={id} href={`#${id}`} className="legal-toc-link">{label}</a>
            ))}
          </aside>

          <main className="legal-content">

            <PolicySection id="acceptance" num="01" title="Acceptance of Terms">
              <p>By accessing or using ForgeCodeHub and any of its tools, calculators, or associated services (collectively, the "Service"), you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the Service.</p>
              <p>These terms apply to all visitors, users, and anyone who interacts with the Service. Your continued use after any changes constitutes acceptance of those changes.</p>
            </PolicySection>

            <PolicySection id="access" num="02" title="Access & Use">
              <p>ForgeCodeHub grants you a non-exclusive, non-transferable, revocable licence to access and use the Service for your personal or internal business purposes, subject to these Terms.</p>
              <ul className="legal-list">
                <li>All tools are provided free of charge. No account or registration is required.</li>
                <li>You may use the tools for personal, educational, and commercial purposes.</li>
                <li>You may not resell, sublicence, or redistribute the Service or its outputs as your own product without written permission.</li>
                <li>We reserve the right to restrict or terminate access to any user who violates these Terms.</li>
              </ul>
            </PolicySection>

            <PolicySection id="ip" num="03" title="Intellectual Property">
              <p>All content on ForgeCodeHub — including tool designs, interface elements, code, branding, logos, copy, and underlying algorithms — is the exclusive property of ForgeCodeHub and its licensors.</p>
              <p>You may not copy, reproduce, modify, reverse-engineer, or create derivative works from any part of the Service without explicit written consent. The ForgeCodeHub name and logo are trademarks and may not be used without permission.</p>
              <p>Outputs generated by our tools (e.g., calculation results) are yours to use freely. The tool code that produced them is not.</p>
            </PolicySection>

            <PolicySection id="conduct" num="04" title="Prohibited Conduct">
              <p>When using ForgeCodeHub, you agree not to:</p>
              <ul className="legal-list">
                <li>Attempt to gain unauthorised access to any part of the Service or its infrastructure</li>
                <li>Use automated bots, scrapers, or crawlers to access or copy the Service at scale</li>
                <li>Introduce malware, viruses, or any malicious code</li>
                <li>Use the Service in any way that violates applicable local, national, or international laws</li>
                <li>Interfere with or disrupt the integrity or performance of the Service</li>
                <li>Reproduce or mirror the Service without prior written authorisation</li>
              </ul>
              <p>Violations may result in immediate termination of access and, where applicable, legal action.</p>
            </PolicySection>

            <PolicySection id="accuracy" num="05" title="Accuracy of Tools">
              <p>Our tools are designed to be accurate and useful, but are provided for informational and educational purposes only. We make no guarantees regarding the accuracy, completeness, or suitability of any tool output for your specific situation.</p>
              <div className="legal-alert-box">
                <p className="legal-alert-title">⚡ Important Notice</p>
                <p>Tool outputs — including financial calculations, tax estimates, and eligibility assessments — should not be treated as professional financial, legal, or tax advice. Always verify results with a qualified professional before making decisions.</p>
              </div>
            </PolicySection>

            <PolicySection id="liability" num="06" title="Limitation of Liability">
              <p>To the fullest extent permitted by law, ForgeCodeHub and its owners, employees, and contributors shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from:</p>
              <ul className="legal-list">
                <li>Your use of or inability to use the Service</li>
                <li>Any errors or inaccuracies in tool outputs</li>
                <li>Decisions made based on tool outputs</li>
                <li>Unauthorised access to or alteration of your data</li>
                <li>Any interruption or cessation of the Service</li>
              </ul>
              <p>Your use of the Service is entirely at your own risk. The Service is provided "as is" and "as available" without warranties of any kind.</p>
            </PolicySection>

            <PolicySection id="changes" num="07" title="Changes to Terms">
              <p>We reserve the right to modify these Terms at any time. When we make significant changes, we will update the "Last updated" date at the top of this page. We may also notify newsletter subscribers of material changes.</p>
              <p>It is your responsibility to review these Terms periodically. Continued use of the Service after any modification constitutes your acceptance of the revised Terms.</p>
            </PolicySection>

            <PolicySection id="governing" num="08" title="Governing Law">
              <p>These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles. Any disputes arising from these Terms or your use of the Service shall be subject to the exclusive jurisdiction of the competent courts.</p>
            </PolicySection>

            <PolicySection id="contact" num="09" title="Contact Us">
              <p>For questions about these Terms, reach out to our team:</p>
              <div className="legal-contact-box">
                <p className="legal-contact-name">ForgeCodeHub Legal</p>
                <p className="legal-contact-email">legal@forgecodehub.com</p>
              </div>
            </PolicySection>

          </main>
        </div>
      </section>

      <footer>
        <a href="/" className="logo">
          <div className="logo-icon" style={{ width: 22, height: 22, fontSize: 11 }}>⚒</div>
          ForgeCodeHub
        </a>
        <div className="footer-links">
          <a href="/privacy">Privacy</a>
          <a href="/terms" style={{ color: "var(--accent)" }}>Terms</a>
          <a href="/disclaimer">Disclaimer</a>
          <a href="https://github.com/forgecodehub" target="_blank" rel="noopener noreferrer">GitHub</a>
          <a href="https://twitter.com/forgecodehub" target="_blank" rel="noopener noreferrer">Twitter</a>
        </div>
        <span>© 2025 ForgeCodeHub</span>
      </footer>
    </>
  );
}

function PolicySection({
  id, num, title, children,
}: {
  id: string; num: string; title: string; children: React.ReactNode;
}) {
  return (
    <div id={id} className="legal-section">
      <div className="legal-section-header">
        <span className="legal-section-num">{num}</span>
        <div className="legal-section-rule" />
      </div>
      <h2 className="legal-section-title">{title}</h2>
      {children}
    </div>
  );
}